server:
  port: 0

spring:
  application:
    name: notification-service

  sleuth:
    integration:
      enabled: true
    sampler:
      probability: 1

  zipkin:
    baseUrl: http://localhost:9411

  # Kafka Properties
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: notificationTopic
    consumer:
      groupId: notificationId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.type.mapping: event:com.tradesphere.notificationservice.OrderPlacedEvent

eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka/